/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tso_appreader_read_util_TSShading */

#ifndef _Included_tso_appreader_read_util_TSShading
#define _Included_tso_appreader_read_util_TSShading
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tso_appreader_read_util_TSShading
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tso_appreader_read_util_TSShading_testHello
  (JNIEnv *, jobject);

/*
 * Class:     tso_appreader_read_util_TSShading
 * Method:    getBase64
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tso_appreader_read_util_TSShading_getBase64__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tso_appreader_read_util_TSShading
 * Method:    getBase64
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tso_appreader_read_util_TSShading_getBase64__
  (JNIEnv *, jobject);

/*
 * Class:     tso_appreader_read_util_TSShading
 * Method:    getImage
 * Signature: (Ltso/appreader/read/util/ImageInfo;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tso_appreader_read_util_TSShading_getImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tso_appreader_read_util_TSShading
 * Method:    getImageByte
 * Signature: (Ltso/appreader/read/util/ImageInfo;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tso_appreader_read_util_TSShading_getImageByte
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
