/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "fw_kit.h"
#include "tclipboard.h"
/* Header for class tso_tnative_TClipBoard */

#ifndef _Included_tso_tnative_TClipBoard
#define _Included_tso_tnative_TClipBoard
#ifdef __cplusplus
extern "C" {
#endif

/*
 *  函数名称:StringToWindowChars
 *  函数功能:将jstring转成UTFchar
 *  函数参数:jstr jstring字符串  winchar UTFchar字符串返回值
 *  函数返回:成功时 返回转换后的字符串 编码格式为UTF-9  0为失败            
 */
static char * StringToWindowChars(JNIEnv * env, jstring jstr)
{
    const char * str = env->GetStringUTFChars(jstr, 0);
    if (str == NULL)
    {
        return 0;
    }

    char * winchar = (char*)ts_malloc(strlen(str)+1);
    strcpy(winchar, str);
    env->ReleaseStringUTFChars(jstr, str);
    return winchar;    
}

/*
 * 将系统剪贴板里的dataFormat格式的数据保存到fileName指定的文件
 */
JNIEXPORT jboolean JNICALL Java_tso_tnative_TLClipBoard_getClipboardContent(JNIEnv *env, jclass cls, jstring fileName, jstring dataFormat)
{    
    jboolean result = JNI_FALSE;
    
    char* pFormat = StringToWindowChars(env, dataFormat);
    char* pFile   = StringToWindowChars(env, fileName);
    if (getSelectionDataToFile(pFormat, pFile))
    {
        result = JNI_TRUE;
    }
    
    //注意释放。
    free(pFormat);
    free(pFile);

    return result;
}

/*
 * 获取系统剪贴板当前数据的格式列表
 */
JNIEXPORT jobjectArray JNICALL Java_tso_tnative_TLClipBoard_getTargets(JNIEnv *env, jclass cls)
{
    vector<string> vecFormats;
    getTargets(vecFormats);
    
    jobjectArray objArray = env->NewObjectArray(vecFormats.size(), env->FindClass("java/lang/Object"), NULL);
    for (int i=0; i<vecFormats.size(); ++i)
    {
        env->SetObjectArrayElement(objArray, i, env->NewStringUTF(vecFormats[i].c_str()));
    }

    return objArray;
}

#ifdef __cplusplus
}
#endif
#endif
