/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tso_tnative_TImage2Screen */

#ifndef _Included_tso_tnative_TImage2Screen
#define _Included_tso_tnative_TImage2Screen
#ifdef __cplusplus
extern "C" {
#endif


/*
 * 将系统剪贴板里的dataFormat格式的数据保存到fileName指定的文件
 */
JNIEXPORT jboolean JNICALL Java_tso_tnative_TImage2Screen_init(JNIEnv *env, jclass cls, jlong xid, jint width, jint height);

/*
 * 获取系统剪贴板当前数据的格式列表
 */
JNIEXPORT jboolean JNICALL Java_tso_tnative_TImage2Screen_update(JNIEnv *env, jclass cls, jbyteArray data);

#ifdef __cplusplus
}
#endif
#endif
