#ifndef _INCLUDED_DIRECT_PAINT
#define _INCLUDED_DIRECT_PAINT

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DIRECT_PAINT */

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_DIRECT_PAINT_setXWindow
    (JNIEnv *, jclass, jlong, jint, jint);

JNIEXPORT void JNICALL Java_tso_tnative_TLinuxImagePaint_paintImage
    (JNIEnv *env, jclass,jint imgWidth,jint imgHeight,jintArray pixels);

#ifdef __cplusplus
}
#endif

#endif